/*ADD CANDIDATE*/
export const ADD_CANDIDATE = "ADD_CANDIDATE";
export const GET_CANDIDATE = "GET_CANDIDATE";

/*VOTER ACTION*/
export const VOTING = "VOTING";

/*LOGIN ACTION*/
export const LOGIN_VOTER = "LOGIN_VOTER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_VOTER = "REGISTER_VOTER";
export const GET_VOTER = "GET_VOTER";
export const LOGOUT_VOTER = "LOGOUT_VOTER";
export const VERIFY_VOTER = "VERIFY_VOTER";

export const LOADING = "LOADING"

/*SESSION lOG*/
export const SESSION_LOG = "SESSION_LOG"